import type { JobOpportunity, TradeMatch } from "@/lib/career/types";

/** Demo openings — not live listings; for UI / flow only. */
const byTrade: Record<string, JobOpportunity[]> = {
  Electrician: [
    {
      id: "el-1",
      title: "Inside Wireman Apprentice — Class of 2026",
      employer: "IBEW Local 134",
      type: "Union",
      location: "Chicago, IL",
      payLabel: "$24–$38/hr (progressive scale)",
      opens: "Applications open Mar–Apr",
      matchHint: "Strong fit for union pathway & indoor/commercial work",
    },
    {
      id: "el-2",
      title: "Residential Electrician Trainee",
      employer: "Summit Electrical Contractors",
      type: "Contractor",
      location: "Phoenix, AZ metro",
      payLabel: "$19–$26/hr to start",
      opens: "Rolling interviews",
      matchHint: "Good if you want smaller crews first",
    },
    {
      id: "el-3",
      title: "Pre-Apprenticeship — Construction Electrician",
      employer: "Arizona Builders Alliance",
      type: "Pre-apprenticeship",
      location: "Mesa, AZ",
      payLabel: "Stipend + PPE provided",
      opens: "Next cohort: Summer",
      matchHint: "Builds hours toward registered apprenticeship",
    },
  ],
  Plumber: [
    {
      id: "pl-1",
      title: "Plumber Apprentice (UA)",
      employer: "UA Local 100",
      type: "Union",
      location: "Dallas–Fort Worth, TX",
      payLabel: "$22–$35/hr scale",
      opens: "Annual intake — check local",
      matchHint: "Commercial & service rotation",
    },
    {
      id: "pl-2",
      title: "Service Plumber Helper",
      employer: "BluePipe Home Services",
      type: "Contractor",
      location: "Atlanta, GA",
      payLabel: "$18–$24/hr + van",
      opens: "Hiring now",
      matchHint: "Fast start if you want customer-facing work",
    },
  ],
  "HVAC Technician": [
    {
      id: "hv-1",
      title: "HVAC Apprentice — Sheet Metal / Service",
      employer: "SMART Local 265",
      type: "Union",
      location: "Milwaukee, WI",
      payLabel: "$21–$32/hr",
      opens: "Spring application window",
      matchHint: "Mix of install & service",
    },
    {
      id: "hv-2",
      title: "Install Tech Trainee (Commercial)",
      employer: "Northland Mechanical",
      type: "Contractor",
      location: "Minneapolis, MN",
      payLabel: "$20–$28/hr",
      opens: "Open until filled",
      matchHint: "Great for tool-forward, team installs",
    },
  ],
  Welder: [
    {
      id: "wd-1",
      title: "Welding Apprentice — Pipe & Structural",
      employer: "UA / Boilermakers joint program",
      type: "Apprenticeship",
      location: "Houston Ship Channel, TX",
      payLabel: "$22–$34/hr",
      opens: "Q2 cohort",
      matchHint: "Heavy fabrication environment",
    },
    {
      id: "wd-2",
      title: "MIG/TIG Trainee — Manufacturing",
      employer: "Great Lakes Fabrication",
      type: "Contractor",
      location: "Cleveland, OH",
      payLabel: "$19–$25/hr",
      opens: "Walk-in Wednesdays",
      matchHint: "Indoor shop + occasional field",
    },
  ],
  Carpenter: [
    {
      id: "ca-1",
      title: "Carpenter Apprentice — Commercial",
      employer: "Carpenters Local 272",
      type: "Union",
      location: "Kansas City, MO",
      payLabel: "$20–$30/hr",
      opens: "Bi-annual",
      matchHint: "Concrete forms & interior systems",
    },
    {
      id: "ca-2",
      title: "Rough Carpenter Helper",
      employer: "Timberline Builders",
      type: "Contractor",
      location: "Denver, CO",
      payLabel: "$18–$23/hr",
      opens: "Immediate",
      matchHint: "Residential & multifamily",
    },
  ],
  "Construction Manager": [
    {
      id: "cm-1",
      title: "Field Engineer → PM Track (Commercial)",
      employer: "Horizon GC Partners",
      type: "Contractor",
      location: "Austin, TX",
      payLabel: "$65K–$78K yr (entry)",
      opens: "Rolling",
      matchHint: "Office + site; great if you like planning",
    },
    {
      id: "cm-2",
      title: "Assistant Superintendent",
      employer: "MetroBuild Inc.",
      type: "Contractor",
      location: "Seattle, WA",
      payLabel: "$70K–$85K yr",
      opens: "2 roles open",
      matchHint: "Coordination-heavy, fast pace",
    },
  ],
  "Heavy Equipment Operator": [
    {
      id: "he-1",
      title: "Operator Apprentice — IUOE",
      employer: "IUOE Local 513",
      type: "Union",
      location: "St. Louis, MO",
      payLabel: "$24–$36/hr",
      opens: "Fall class",
      matchHint: "Earthmoving & civil sites",
    },
    {
      id: "he-2",
      title: "Equipment Trainee (CDL path)",
      employer: "Blacktop Hauling Co.",
      type: "Contractor",
      location: "Nashville, TN",
      payLabel: "$22–$28/hr",
      opens: "Now",
      matchHint: "Dump & loader focus first 6 mo",
    },
  ],
  Pipefitter: [
    {
      id: "pf-1",
      title: "Pipefitter Apprentice — UA",
      employer: "UA Local 597",
      type: "Union",
      location: "Chicago, IL",
      payLabel: "$26–$40/hr",
      opens: "Lottery system — watch dates",
      matchHint: "Industrial & steam systems",
    },
    {
      id: "pf-2",
      title: "Pipefitter Helper — Data Center build",
      employer: "Vertex Industrial",
      type: "Contractor",
      location: "Northern VA",
      payLabel: "$24–$32/hr",
      opens: "Project-based",
      matchHint: "Tight specs, clean rooms",
    },
  ],
  Ironworker: [
    {
      id: "ir-1",
      title: "Ironworker Apprentice — Reinforcing",
      employer: "Ironworkers Local 63",
      type: "Union",
      location: "Detroit, MI",
      payLabel: "$23–$36/hr",
      opens: "Spring",
      matchHint: "Heights & structural steel",
    },
    {
      id: "ir-2",
      title: "Rodbuster / Ironworker Trainee",
      employer: "SteelRise Erectors",
      type: "Contractor",
      location: "Miami, FL",
      payLabel: "$20–$27/hr",
      opens: "Open",
      matchHint: "Outdoor, high-energy crews",
    },
  ],
  "Sheet Metal Worker": [
    {
      id: "sm-1",
      title: "Sheet Metal Apprentice",
      employer: "SMART Local 265",
      type: "Union",
      location: "Milwaukee, WI",
      payLabel: "$21–$33/hr",
      opens: "Annual",
      matchHint: "Duct fabrication & install",
    },
  ],
  "Elevator Mechanic": [
    {
      id: "em-1",
      title: "NEIEP Elevator Constructor Apprentice",
      employer: "IUEC Local 10",
      type: "Union",
      location: "Boston, MA",
      payLabel: "Top-scale program",
      opens: "Once/year — aptitude test",
      matchHint: "Math-heavy; long apprenticeship",
    },
    {
      id: "em-2",
      title: "Elevator Helper — Modernization crew",
      employer: "Vertical Systems Co.",
      type: "Contractor",
      location: "New York, NY",
      payLabel: "$28–$38/hr",
      opens: "Referral",
      matchHint: "Urban high-rise environment",
    },
  ],
  Boilermaker: [
    {
      id: "bo-1",
      title: "Boilermaker Apprentice",
      employer: "International Brotherhood of Boilermakers",
      type: "Union",
      location: "Mobile, AL (regional travel)",
      payLabel: "$25–$38/hr + per diem",
      opens: "Travel projects",
      matchHint: "Shutdown & industrial boilers",
    },
  ],
  "Solar Installer": [
    {
      id: "so-1",
      title: "Solar Installer / Electrician trainee",
      employer: "SunPath Renewables",
      type: "Contractor",
      location: "Riverside County, CA",
      payLabel: "$20–$28/hr",
      opens: "High volume season",
      matchHint: "Roof work + electrical tie-in",
    },
    {
      id: "so-2",
      title: "PV Apprenticeship (NABCEP path)",
      employer: "GreenGrid Training Partners",
      type: "Apprenticeship",
      location: "Las Vegas, NV",
      payLabel: "Earn while you learn",
      opens: "Quarterly",
      matchHint: "Good with tech + outdoor work",
    },
  ],
  "Wind Turbine Technician": [
    {
      id: "wt-1",
      title: "Wind Tech Trainee — O&M",
      employer: "Prairie Wind Services",
      type: "Contractor",
      location: "Amarillo, TX region",
      payLabel: "$24–$32/hr",
      opens: "Climb test required",
      matchHint: "Travel & heights",
    },
  ],
  "Industrial Maintenance Mechanic": [
    {
      id: "im-1",
      title: "Maintenance Mechanic Apprentice",
      employer: "FMC Industrial Union",
      type: "Union",
      location: "Gary, IN",
      payLabel: "$25–$37/hr",
      opens: "Plant seniority rules",
      matchHint: "Rotating equipment & troubleshooting",
    },
    {
      id: "im-2",
      title: "Multi-Craft Technician Trainee",
      employer: "Midwest Packaging Group",
      type: "Contractor",
      location: "Columbus, OH",
      payLabel: "$22–$30/hr",
      opens: "2nd shift",
      matchHint: "PLC basics + mechanical",
    },
  ],
  "Brick/Stonemason": [
    {
      id: "br-1",
      title: "Bricklayer Apprentice — BAC",
      employer: "BAC Local 4",
      type: "Union",
      location: "Philadelphia, PA",
      payLabel: "$21–$31/hr",
      opens: "Spring",
      matchHint: "Outdoor, precision layout",
    },
  ],
  Cosmetologist: [
    {
      id: "co-1",
      title: "Licensed Cosmetology Apprentice (salon)",
      employer: "Studio North Collective",
      type: "Contractor",
      location: "Portland, OR",
      payLabel: "$16–$22/hr + tips",
      opens: "Rolling",
      matchHint: "Client-facing, flexible schedule",
    },
  ],
};

const genericFallback: JobOpportunity[] = [
  {
    id: "gen-1",
    title: "Registered Apprenticeship — search by trade",
    employer: "apprenticeship.gov",
    type: "Apprenticeship",
    location: "Your state",
    payLabel: "Varies by program",
    opens: "Year-round",
    matchHint: "Start here to verify programs near you",
  },
  {
    id: "gen-2",
    title: "Union hall information session",
    employer: "Local trade union",
    type: "Union",
    location: "Nearest metro",
    payLabel: "Free to attend",
    opens: "Monthly",
    matchHint: "Ask about aptitude test dates",
  },
];

export function getJobsForTrade(tradeName: string): JobOpportunity[] {
  return byTrade[tradeName] ?? genericFallback;
}

/** Merge demo jobs for stored matches that predate `sampleJobs`. */
export function enrichMatchesWithJobs(result: { matches: TradeMatch[] }): { matches: TradeMatch[] } {
  return {
    matches: result.matches.map((m) => ({
      ...m,
      sampleJobs: m.sampleJobs?.length ? m.sampleJobs : getJobsForTrade(m.trade),
    })),
  };
}

/** A few mixed trades for the marketing / landing strip. */
export function getFeaturedJobs(): JobOpportunity[] {
  return [
    byTrade.Electrician[0],
    byTrade["HVAC Technician"][0],
    byTrade["Construction Manager"][0],
  ];
}
